Feature/vaccinecer 2404
admin-ch/CovidCertificate-Management-UI pull request #259
Opened 2023-01-12 15:33 UTC by YanikFenner

2023-01-20 07:11 UTC, haraldloesing reviewed
Over all it looks good. But can you please maintain the hints from GitHub Actions (inline comments). And also please fix the 4 code smells that Sonar found.

2023-01-23 08:02 UTC, haraldloesing approved these changes

2023-01-23 10:02 UTC, ndinat requested changes

2023-01-23 10:02 UTC, ndinat commented on src/app/cache-reset/cache-reset.service.ts
> +			this.notificationService.success(' ');
Würde hier anstatt `' '` ein Objekt übergeben: `{title: 'Caches zurückgesetzt'}` (oder so) Dann siehst es auch nicht aus als ob im Toast etwas fehlt.

2023-01-23 11:40 UTC, ndinat approved these changes

2023-01-23 12:58 UTC, merged